version: '3'
services:
  app:
    image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: |
      npm start